---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world-three
  namespace: hello-world
spec:
  containers:
  - name: hello-three
    image: ubuntu:latest
    command: ["bash"]
    args:
      - -c
      - |
        seconds=0
        while true; do
          echo "Hello World from hello-world-three! I've been running for $seconds seconds"
          sleep 5
          seconds=$(( $seconds + 5 ))
        done
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
