---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world-two
  namespace: {{ .Values.namespace }}
spec:
  containers:
  - name: hello-two
    image: ubuntu
    command: ["bash"]
    args:
      - -c
      - |
        seconds=0
        while true; do
          echo "Hello World from hello-world-two!"
          echo "hello-world-two has been alive for $seconds seconds"
          echo " "
          sleep 5
          seconds=$(($seconds + 5))
        done
